# Generated by Django 3.1.7 on 2022-02-26 09:55

from django.db import migrations, models
import greate_ocean.yandex_s3_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('image', models.FileField(storage=greate_ocean.yandex_s3_storage.ClientDocsStorage(), upload_to='')),
            ],
        ),
    ]
