# Generated by Django 3.1.7 on 2022-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fish',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fish',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
