# Generated by Django 3.1.7 on 2022-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220226_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fish',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
