# Generated by Django 3.1.7 on 2022-04-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220227_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='type',
        ),
    ]
