# Generated by Django 3.1.7 on 2022-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_fish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('fishes', models.ManyToManyField(blank=True, null=True, to='main.Fish')),
            ],
        ),
    ]
