# Generated by Django 3.1.7 on 2022-04-20 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_friends', to='main.User'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 20, 17, 36, 25, 359534))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='fish',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='main.Comment'),
        ),
    ]
