# Generated by Django 3.1.7 on 2022-04-21 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220420_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 19, 56, 3, 175283)),
        ),
    ]
